spring.datasource.url:jdbc:mysql://localhost:3306/mercadoficio3
spring.datasource.username:root
spring.datasource.password:root
spring.datasource.driver-class-name:com.mysql.cj.jdbc.Driver
spring.jpa.show-sql:true
spring.jpa.hibernate.ddl-auto: update
spring.jpa.properties.hibernate.dialect:
org.hibernate.dialect.MySQL5InnoDBDialect
spring.security.oauth2.resourceserver.jwt.issuer-uri: https://dev-d44eq7wqicvd1cfr.us.auth0.com/
spring.security.oauth2.resourceserver.jwt.audience : https://MercadOficio
spring.emailApi.key=re_dCqgFwcT_BDxRZWwLLKF9UM9ppVV49vhr