spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER_NAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-d44eq7wqicvd1cfr.us.auth0.com/
spring.security.oauth2.resourceserver.jwt.audience=https://MercadOficio
spring.emailApi.key=re_dCqgFwcT_BDxRZWwLLKF9UM9ppVV49vhr